### ISSUE TITLE
Getting a failure when I run

### ISSUE THREAD

**Issue by RicknTx** [jessepeterson/autopkg-recipes#3]
Error:  Error in com.github.jessepeterson.munki.VirtualBox: Processor: VirtualBoxURLProvider: Error: No matching VirtualBox software.

Hi,

I'm wondering if Oracle changed something on this.  It is failing to build when I run autopkg this week.  I did a refresh on my side with autopkg and it didn't make an impact.  I don't see any updates on the recipe here.

Are you still having success with this?  

Thanks for the great recipe!

**Comment by jessepeterson** [comment]
As @RicknTx pointed out this is tracked under autopkg/jessepeterson-recipes#11. Closing this issue while tracking in autopkg repo.
