### ISSUE TITLE
Not getting latest stable

### ISSUE THREAD

**Issue by laapsaap** [jessepeterson/autopkg-recipes#4]
https://update.virtualbox.org/query.php?platform=DARWIN_64BITS_GENERIC&version=4.3.16_95972&count=97&branch=stable

and 

http://download.virtualbox.org/virtualbox/LATEST.TXT

are not the same anymore. So I think the query method is currently broken after 5.0.30

**Comment by jessepeterson** [comment]
I think you might be using an outdated set of recipes. I think you want to be using these: https://github.com/autopkg/jessepeterson-recipes

If it's still not working feel free to hit me up on that recipe. Cheers!
