### ISSUE TITLE
VirtualBoxExtPack Munki install stuck at postinstall script

### ISSUE THREAD

**Issue by MichalMMac** [jessepeterson/autopkg-recipes#5]
Hello,

I am currently testing deployment of VirtualBox 5.1.20 (version from last week).
When Munki tries to install VirtualBoxExtPack it gets stuck when running postinstall script.

Specifically it's this command:
```
/Applications/VirtualBox.app/Contents/MacOS/VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
```

Anyone else seeing this?

**Comment by MichalMMac** [comment]
`5.1.18` installs without any issues.

**Comment by jessepeterson** [comment]
Hello @MichalMMac! I have not seen this issue. But also FYI this repository isn't the correct one. You want github.com/autopkg/jessepeterson-recipe and is actually a duplicate of https://github.com/autopkg/jessepeterson-recipes/issues/47 :)
